Restaurant Delivery Service
Goal Description: Allocate and route vehicles for a restaurant delivery service.
Fleet Size: 5 (Requesting a fleet of 5 delivery vehicles)

The result:
I wrote all the code, however the code is not being run and I personally could not find the answer. Moreover, there are some problems with colcon library that should be dealt internally and major problem of the project is also with colcon library.

